baseURL = "/"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
title = "My New Hugo Site"
# theme = "seb-doc"
timeout = 600_000
enableRobotsTXT = true

[[module.imports]]
path = "github.com/hugo-mods/lazyimg"
[[module.imports]]
path = "github.com/matharel/seb-doc"

[params]
breadcrumbDepth = 0
breadcrumb = 2
gitAccount = "https://github.dev/matharel/au-son-du-diois/blob/main/content/"

  [params.lazyimg]
  resizer = "auto"
  renderer = "lqip-webp"
  lqipSize = "120x Gaussian"
  maxSize = "1920x"
  resizeOptions = "Lanczos q95"
  class = "my-img-class"
  alt = "My logo"
  noscript = true
  errorHandler = "warning-remote"

[security.exec]
allow = [
  "^dart-sass-embedded$",
  "^go$",
  "^npx$",
  "^postcss$",
  "^asciidoctor$"
]
osEnv = [ "(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$" ]

[security.funcs]
getenv = [ "^HUGO_" ]

[security.http]
methods = [ "(?i)GET|POST" ]
urls = [ ".*" ]

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.renderer]
unsafe = true
hardWraps = true

[caches.getjson]
dir = ":cacheDir/:project"
maxAge = -1

[caches.getcsv]
dir = ":cacheDir/:project"
maxAge = -1

[caches.images]
dir = ":cacheDir/images"
maxAge = "1440h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = -1
