[build.environment]
HUGO_VERSION = "0.134.2"
TZ = "Europe/Paris"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[build]
publish = "public"
command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/1.79.2/dart-sass-1.79.2-linux-x64.tar.gz && \
  tar -xf dart-sass-1.79.2-linux-x64.tar.gz && \
  rm dart-sass-1.79.2-linux-x64.tar.gz && \
  export PATH=$(pwd)/dart-sass:$PATH && \
  hugo --gc --minify \
  """

[build.cache]
  # Ajouter le chemin du répertoire où vous stockez vos images converties
  paths = ["resources/_gen/images", "public/**"]
